// PasswordController action stub for Electron build
// These actions are auto-generated by Laravel Wayfinder in the web app

const PasswordController = {
    update: {
        url: '/settings/password',
        method: 'PUT' as const,
    },
};

export default PasswordController;
