// ProfileController action stub for Electron build
// These actions are auto-generated by Laravel Wayfinder in the web app

const ProfileController = {
    update: {
        url: '/settings/profile',
        method: 'PATCH' as const,
    },
    destroy: {
        url: '/settings/profile',
        method: 'DELETE' as const,
    },
};

export default ProfileController;
