// Stub routes file for Electron standalone build
// These routes are auto-generated by Laravel Wayfinder in the web app,
// but need to be provided manually for the Electron desktop app.

type RouteFunction = () => string;

// Helper to create route functions
const createRoute = (path: string): RouteFunction => () => path;

// Main routes
export const home = createRoute('/');
export const dashboard = createRoute('/dashboard');
export const login = createRoute('/login');
export const register = createRoute('/register');
export const logout = createRoute('/logout');

// Tension records routes
export const tensionRecordsDisplay = createRoute('/tension-records-display');
export const twistingTensionMain = createRoute('/twisting-tension-main');
export const weavingTensionMain = createRoute('/weaving-tension-main');

// Stock take routes
export const stockTakeRecordsMain = createRoute('/stock-take-records-main');
export const batchStockTakingMain = createRoute('/batch-stock-taking-main');

// Other routes
export const userMaintenance = createRoute('/user-maintenance');
export const finishEarlierDisplay = createRoute('/finish-earlier-display');
export const underConstruction = createRoute('/under-construction');
export const databaseSync = createRoute('/database-sync');

// Settings routes (nested module simulation)
export * from './profile';
export * from './password';
export * from './appearance';
export * from './two-factor';
