// AuthenticatedSessionController action stub for Electron build
// These actions are auto-generated by Laravel Wayfinder in the web app

const AuthenticatedSessionController = {
    store: {
        url: '/login',
        method: 'POST' as const,
    },
    destroy: {
        url: '/logout',
        method: 'POST' as const,
    },
};

export default AuthenticatedSessionController;
