// EmailVerificationNotificationController action stub for Electron build
// These actions are auto-generated by Laravel Wayfinder in the web app

const EmailVerificationNotificationController = {
    store: {
        url: '/email/verification-notification',
        method: 'POST' as const,
    },
};

export default EmailVerificationNotificationController;
