// NewPasswordController action stub for Electron build
// These actions are auto-generated by Laravel Wayfinder in the web app

const NewPasswordController = {
    store: {
        url: '/reset-password',
        method: 'POST' as const,
    },
};

export default NewPasswordController;
