// PasswordResetLinkController action stub for Electron build
// These actions are auto-generated by Laravel Wayfinder in the web app

const PasswordResetLinkController = {
    store: {
        url: '/forgot-password',
        method: 'POST' as const,
    },
};

export default PasswordResetLinkController;
