// RegisteredUserController action stub for Electron build
// These actions are auto-generated by Laravel Wayfinder in the web app

const RegisteredUserController = {
    store: {
        url: '/register',
        method: 'POST' as const,
    },
};

export default RegisteredUserController;
