// GENERATED by tool/oklch_to_hex.dart from the web app resources/css/app.css. Do not edit.
import 'dart:ui';

/// Base radius (--radius: 0.625rem) in logical pixels.
const double kRadius = 10.0;

class TokenSet {
  const TokenSet({
    required this.background,
    required this.foreground,
    required this.card,
    required this.cardForeground,
    required this.popover,
    required this.popoverForeground,
    required this.primary,
    required this.primaryForeground,
    required this.secondary,
    required this.secondaryForeground,
    required this.muted,
    required this.mutedForeground,
    required this.accent,
    required this.accentForeground,
    required this.destructive,
    required this.destructiveForeground,
    required this.border,
    required this.input,
    required this.ring,
    required this.chart1,
    required this.chart2,
    required this.chart3,
    required this.chart4,
    required this.chart5,
    required this.sidebar,
    required this.sidebarForeground,
    required this.sidebarPrimary,
    required this.sidebarPrimaryForeground,
    required this.sidebarAccent,
    required this.sidebarAccentForeground,
    required this.sidebarBorder,
    required this.sidebarRing,
  });
  final Color background;
  final Color foreground;
  final Color card;
  final Color cardForeground;
  final Color popover;
  final Color popoverForeground;
  final Color primary;
  final Color primaryForeground;
  final Color secondary;
  final Color secondaryForeground;
  final Color muted;
  final Color mutedForeground;
  final Color accent;
  final Color accentForeground;
  final Color destructive;
  final Color destructiveForeground;
  final Color border;
  final Color input;
  final Color ring;
  final Color chart1;
  final Color chart2;
  final Color chart3;
  final Color chart4;
  final Color chart5;
  final Color sidebar;
  final Color sidebarForeground;
  final Color sidebarPrimary;
  final Color sidebarPrimaryForeground;
  final Color sidebarAccent;
  final Color sidebarAccentForeground;
  final Color sidebarBorder;
  final Color sidebarRing;
}

const lightTokens = TokenSet(
  background: Color(0xFFFFFFFF),
  foreground: Color(0xFF0A0A0A),
  card: Color(0xFFFFFFFF),
  cardForeground: Color(0xFF0A0A0A),
  popover: Color(0xFFFFFFFF),
  popoverForeground: Color(0xFF0A0A0A),
  primary: Color(0xFF171717),
  primaryForeground: Color(0xFFFAFAFA),
  secondary: Color(0xFFF5F5F5),
  secondaryForeground: Color(0xFF171717),
  muted: Color(0xFFF5F5F5),
  mutedForeground: Color(0xFF737373),
  accent: Color(0xFFF5F5F5),
  accentForeground: Color(0xFF171717),
  destructive: Color(0xFFE7000B),
  destructiveForeground: Color(0xFFE7000B),
  border: Color(0xFFE5E5E5),
  input: Color(0xFFE5E5E5),
  ring: Color(0xFFD4D4D4),
  chart1: Color(0xFFF54900),
  chart2: Color(0xFF009689),
  chart3: Color(0xFF104E64),
  chart4: Color(0xFFFFB900),
  chart5: Color(0xFFFE9A00),
  sidebar: Color(0xFFFAFAFA),
  sidebarForeground: Color(0xFF0A0A0A),
  sidebarPrimary: Color(0xFF171717),
  sidebarPrimaryForeground: Color(0xFFFAFAFA),
  sidebarAccent: Color(0xFFF5F5F5),
  sidebarAccentForeground: Color(0xFF171717),
  sidebarBorder: Color(0xFFE5E5E5),
  sidebarRing: Color(0xFFD4D4D4),
);

const darkTokens = TokenSet(
  background: Color(0xFF0A0A0A),
  foreground: Color(0xFFFAFAFA),
  card: Color(0xFF0A0A0A),
  cardForeground: Color(0xFFFAFAFA),
  popover: Color(0xFF0A0A0A),
  popoverForeground: Color(0xFFFAFAFA),
  primary: Color(0xFFFAFAFA),
  primaryForeground: Color(0xFF171717),
  secondary: Color(0xFF262626),
  secondaryForeground: Color(0xFFFAFAFA),
  muted: Color(0xFF262626),
  mutedForeground: Color(0xFFA1A1A1),
  accent: Color(0xFF262626),
  accentForeground: Color(0xFFFAFAFA),
  destructive: Color(0xFF82181A),
  destructiveForeground: Color(0xFFFB2C36),
  border: Color(0xFF262626),
  input: Color(0xFF262626),
  ring: Color(0xFF525252),
  chart1: Color(0xFF1447E6),
  chart2: Color(0xFF00BC7D),
  chart3: Color(0xFFFE9A00),
  chart4: Color(0xFFAD46FF),
  chart5: Color(0xFFFF2056),
  sidebar: Color(0xFF171717),
  sidebarForeground: Color(0xFFFAFAFA),
  sidebarPrimary: Color(0xFFFAFAFA),
  sidebarPrimaryForeground: Color(0xFFFAFAFA),
  sidebarAccent: Color(0xFF262626),
  sidebarAccentForeground: Color(0xFFFAFAFA),
  sidebarBorder: Color(0xFF262626),
  sidebarRing: Color(0xFF525252),
);
