// Generates lib/core/theme/tokens.g.dart from the web app's resources/css/app.css.
// Usage (from mobile/): dart run tool/oklch_to_hex.dart [path/to/app.css]
import 'dart:io';
import 'dart:math' as math;

String toHex(double l, double c, double hDeg) {
  final h = hDeg * math.pi / 180;
  final a = c * math.cos(h), b = c * math.sin(h);
  final l_ = math.pow(l + 0.3963377774 * a + 0.2158037573 * b, 3).toDouble();
  final m_ = math.pow(l - 0.1055613458 * a - 0.0638541728 * b, 3).toDouble();
  final s_ = math.pow(l - 0.0894841775 * a - 1.2914855480 * b, 3).toDouble();
  final r = 4.0767416621 * l_ - 3.3077115913 * m_ + 0.2309699292 * s_;
  final g = -1.2684380046 * l_ + 2.6097574011 * m_ - 0.3413193965 * s_;
  final bl = -0.0041960863 * l_ - 0.7034186147 * m_ + 1.7076147010 * s_;
  int enc(double v) {
    v = v.clamp(0.0, 1.0);
    final s = v <= 0.0031308 ? 12.92 * v : 1.055 * math.pow(v, 1 / 2.4) - 0.055;
    return (s * 255).round().clamp(0, 255);
  }
  String x(int n) => n.toRadixString(16).padLeft(2, '0');
  return '0xFF${x(enc(r))}${x(enc(g))}${x(enc(bl))}'.toUpperCase().replaceFirst('0XFF', '0xFF');
}

String camel(String kebab) {
  final p = kebab.split('-');
  return p.first + p.skip(1).map((s) => s[0].toUpperCase() + s.substring(1)).join();
}

Map<String, String> parseBlock(String css, String selector) {
  final start = css.indexOf('$selector {');
  final end = css.indexOf('}', start);
  final body = css.substring(start, end);
  final out = <String, String>{};
  final color = RegExp(r'--([a-z0-9-]+):\s*oklch\(([\d.]+)\s+([\d.]+)\s+([\d.]+)\)');
  for (final m in color.allMatches(body)) {
    out[camel(m[1]!)] = toHex(double.parse(m[2]!), double.parse(m[3]!), double.parse(m[4]!));
  }
  return out;
}

void main(List<String> args) {
  // Default: the web app's stylesheet one level up in the monorepo (run from `mobile/`).
  final path = args.isNotEmpty ? args.first : '../resources/css/app.css';
  final css = File(path).readAsStringSync();
  final light = parseBlock(css, ':root');
  final dark = parseBlock(css, '.dark');
  final radius = RegExp(r'--radius:\s*([\d.]+)rem').firstMatch(css)![1]!;
  final buf = StringBuffer()
    ..writeln('// GENERATED by tool/oklch_to_hex.dart from the web app resources/css/app.css. Do not edit.')
    ..writeln("import 'dart:ui';")
    ..writeln()
    ..writeln('/// Base radius (--radius: ${radius}rem) in logical pixels.')
    ..writeln('const double kRadius = ${(double.parse(radius) * 16)};')
    ..writeln()
    ..writeln('class TokenSet {')
    ..writeln('  const TokenSet({');
  for (final k in light.keys) {
    buf.writeln('    required this.$k,');
  }
  buf.writeln('  });');
  for (final k in light.keys) {
    buf.writeln('  final Color $k;');
  }
  buf.writeln('}');
  for (final e in {'lightTokens': light, 'darkTokens': dark}.entries) {
    buf.writeln('\nconst ${e.key} = TokenSet(');
    for (final k in light.keys) {
      buf.writeln('  $k: Color(${e.value[k]}),');
    }
    buf.writeln(');');
  }
  File('lib/core/theme/tokens.g.dart').writeAsStringSync(buf.toString());
  stdout.writeln('wrote tokens.g.dart (${light.length} light / ${dark.length} dark tokens)');
}
